project:
  type: website
  output-dir: "_site"
    
website:
  title: "Dr. Jihong Zhang"
  site-url: "https://www.jihongzhang.org/"
  favicon: "images/icon.png"
  description: "Technical and Statistical but Fun"
  google-analytics:
    tracking-id: "UA-149871707-1"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  twitter-card: 
    creator: "@jihongzgamma"
  open-graph: true
  page-footer: "Copyright 2015-2024, JihongZhang" 
  sidebar:
    style: "floating"
    contents:
      - section: 'Lecture Slides'
        contents: Lecture*.qmd
  navbar:
    background: '#CEB8A6'
    collapse-below: lg
    pinned: true
    title: false
    right:
      - text: "Home"
        icon: 'bi bi-house' # https://icons.getbootstrap.com
        file: index.qmd
      - text: "Blog"     
        icon: 'bi bi-pencil-square'
        file: posts.qmd 
      - text: "Dashboard"
        icon: "bi bi-speedometer2"
        file: dashboards/template.qmd  
      - text: C.V.
        icon: "bi bi-person" # somehow the file path only works in nav. bar, not link in index
        file: uploads/Curriculum_Vitae.pdf
      - text: "More"
        icon: 'bi bi-three-dots'
        menu:
          - projects.qmd
          - links.qmd
    
format:
  html:
    theme: 
      light: [cosmo, rwds.scss] # https://bootswatch.com/5/minty/_variables.scss
      dark: [darkly, rwds-dark.scss]
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
    comments:
      giscus:
        repo: JihongZ/quarto-academic-jihong
    header-includes: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
      <script src="https://cdn.jsdelivr.net/npm/@xiee/utils/js/key-buttons.min.js" defer></script>
      <link href="https://cdn.jsdelivr.net/npm/@xiee/utils/css/key-buttons.min.css" rel="stylesheet">
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap" rel="stylesheet">
    mainfont: 'Taub Sans'
    fontsize: 1em
    html-math-method: katex
    # code settings
    monofont: 'JetBrains Mono'
    code-link: true
    code-summary: '&#8984;+C' # https://symbl.cc/en/collections/special-symbols/
    code-line-numbers: false
    code-overflow: wrap
    linestretch: 1.5
    # toc
    toc: true
    table-of-contents: true
    toc-location: right
    fig-cap-location: margin # put captions of figure in the margin
    reference-location: margin
    citation-location: margin
    footnotes-hover: true
    
    
editor: visual

execute: 
  freeze: true
