project:
  type: website
  output-dir: _site

website:
  title: "Dr. Jihong Zhang"
  site-url: "https://www.jihongzhang.org/"
  favicon: icon.png
  description: "Technical and Statistical but Fun"
  google-analytics:
    tracking-id: "UA-149871707-1"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card: 
    creator: "@jihongzgamma"
  open-graph: true
  page-footer: "Copyright 2015-2023, @JihongZ" 
  # sidebar:
  #   style: "floating"
  #   contents:
  #     - section: Contents
  #       contents:
  #         - auto: '*.qmd'
  navbar:
    background: '#008080'
    collapse-below: lg
    pinned: true
    title: false
    right:
      - text: "Home"
        icon: 'bi bi-house' # https://icons.getbootstrap.com
        file: index.qmd
      - text: "Blog"     
        icon: 'bi bi-file-post-fill'
        file: posts.qmd  
      - text: "More"
        icon: 'bi bi-three-dots-vertical'
        menu:
          - projects.qmd
          - links.qmd
      - icon: rss
        href: index.xml
  
format:
  html:
    theme: 
      light: [Cosmo, rwds.scss] # https://bootswatch.com/5/minty/_variables.scss
      dark: [Cyborg, rwds-dark.scss]
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 750px
      margin-width: 250px
    comments:
      giscus:
        repo: JihongZ/quarto-academic-jihong
        theme: preferred_color_scheme
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@500&family=Oxygen+Mono&family=Ysabeau+Office&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
      <script src="https://cdn.jsdelivr.net/npm/@xiee/utils/js/key-buttons.min.js" defer></script>
      <link href="https://cdn.jsdelivr.net/npm/@xiee/utils/css/key-buttons.min.css" rel="stylesheet">
    mainfont: 'Ysabeau Office'
    html-math-method: katex
    # code settings
    monofont: 'JetBrains Mono'
    code-link: true
    code-summary: '&#8984;+C' # https://symbl.cc/en/collections/special-symbols/
    code-line-numbers: false
    code-overflow: wrap
    linestretch: 1.5
    # toc
    table-of-contents: true
    toc-location: right
    fontsize: 1em
    
editor: visual

execute: 
  freeze: auto
